package main

import (
	"log"
	"net/http"

	_ "github.com/nileshkorpad1/simple-blog/docs" // docs is generated by Swag CLI

	"github.com/nileshkorpad1/simple-blog/controllers"

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

//handle API Requests
func handleRequests() {

	apiRouter := mux.NewRouter().StrictSlash(true)
	apiRouter.HandleFunc("/api/v1/articles", controllers.CreateArticle).Methods("POST")
	apiRouter.HandleFunc("/api/v1/articles/", controllers.GetArticles).Methods("GET")
	apiRouter.HandleFunc("/api/v1/articles/{id}", controllers.GetArticle).Methods("GET")

	// Swagger
	apiRouter.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)

	log.Fatal(http.ListenAndServe(":8080", apiRouter))
}

// entry point

// @title Articles API
// @version 1.0
// @description This is a sample serice for managing Articles
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email nileshkorpad@gmail.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath /
func main() {
	// connect db

	handleRequests()
}
