package main

import (
	"log"
	"net/http"

	_ "github.com/nileshkorpad1/simple-blog/docs" // docs is generated by Swag CLI

	"github.com/nileshkorpad1/simple-blog/controllers"

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

//handle API Requests
func handleRequests() {

	apiRouter := mux.NewRouter().StrictSlash(true)
	apiRouter.HandleFunc("/api/v1/articles", controllers.CreateArticle).Methods("POST")
	apiRouter.HandleFunc("/api/v1/articles/", controllers.GetArticles).Methods("GET")
	apiRouter.HandleFunc("/api/v1/articles/{id}", controllers.GetArticle).Methods("GET")

	// Swagger
	apiRouter.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)

	log.Fatal(http.ListenAndServe(":8080", apiRouter))
}

// entry point
func main() {
	// connect db

	handleRequests()
}
